"""Phase 16.5 — build and gate the 2026 situation-change event board.

    uv run python steps/phase16_5_situation_events.py            # validate the committed board
    uv run python steps/phase16_5_situation_events.py --write    # regenerate it

Unlike 16.3's `reference/coaches.csv` — which has no free source and so must be hand-curated — the
event board is **derived**. Who plays where next season is pinned down by three tables already in
the warehouse (the 2026 ADP board, the 2026 consensus projections, and 2025 `weekly`), so the rows
are generated and the human contribution is narrowed to what no feed carries: the *mechanism* of
each move and its terms. Those live in ``ANNOTATIONS`` below and are merged onto the derived rows.

The first cut of this file was hand-assembled from offseason trackers and came to 9 rows; it missed
16 of the 23 team changes among draftable players. That is the failure this step exists to prevent:
the board is now exhaustive at a stated ADP cutoff, and the gates below fail if it stops being so.

Read-only against the warehouse, and walled off from the frozen value stack.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pandas as pd

from fantasy_quant.data import db
from fantasy_quant.situation import events as E

OUT = Path(__file__).resolve().parents[1] / "analysis" / "phase16_5_situation_events.json"
TARGET = 2026

#: Hand research, re-verified 2026-07-25. Only `mechanism` / `confidence` / `notes` — never *who* or
#: *where*, which the derivation owns and cross-checks. `confidence` grades the ANNOTATION alone.
ANNOTATIONS = pd.DataFrame([
    ("Kenneth Walker III", "free_agent", "high",
     "3yr/$45M ($28M gtd) from SEA; lead back, career-high volume projected [RotoWire/Yahoo]"),
    ("Jaylen Waddle", "trade", "high",
     "DEN sent 2026 1st (#30), 3rd (#94), 4th (#130); got Waddle + a 2026 4th (#111) "
     "[Broncos.com/ESPN]"),
    ("Wan'Dale Robinson", "free_agent", "high", "4yr/$78M; TEN slot/target hog [NBC/CBS]"),
    ("David Montgomery", "trade", "high",
     "HOU sent G Juice Scruggs + a 2026 4th + a 2027 7th [CBS trade tracker]"),
    ("Isiah Pacheco", "free_agent", "high",
     "1yr deal; reported as top BACKUP to Gibbs, not a true committee — sizing the split is the "
     "open question [RotoWire]"),
    ("Michael Pittman Jr.", "trade", "high",
     "PIT sent a 6th and got a 7th back; leaves a WR hole in IND [CBS trade tracker]"),
    ("Kyler Murray", "free_agent", "high",
     "new starting QB for MIN — a situation change for Jefferson/Addison, and the ARI side too "
     "[RotoWire/Yahoo]"),
    ("Tyler Allgeier", "free_agent", "low",
     "2yr/$12.25M reported [NBC/AOL]; NOT re-confirmed 2026-07-25. Crowded ARI backfield w/ Benson "
     "+ Conner. VERIFY"),
], columns=["player", "mechanism", "confidence", "notes"])

#: Researched in the first cut but **not** an event under the derivation — kept as an explicit
#: record so the disagreement is reviewable rather than silently dropped.
WITHDRAWN = {
    "Aaron Jones Sr.": "re-signed with MIN; no team change, no MIN RB-room churn. The original "
                       "premise was a timeshare with Jordan Mason, but that trade closed 16 Mar "
                       "2025 — the derivation independently reaches the same 'not a 2026 event' "
                       "conclusion the manual re-verification did.",
}


def _header(con, out: pd.DataFrame) -> str:
    snap = con.execute("SELECT max(snapshot_date) FROM adp_snapshots "
                       "WHERE season = ? AND source = 'ffc'", [TARGET]).fetchone()[0]
    n_unknown = int((out["mechanism"] == "unknown").sum())
    n_soft = int((out["confidence"] != "high").sum())
    return f"""\
# Phase 16.5 — {TARGET} situation-change event board. ONE ROW PER AFFECTED DRAFTABLE PLAYER.
# GENERATED by situation/events.py on 2026-07-25 — do NOT hand-edit rows. Re-run
#   `uv run python steps/phase16_5_situation_events.py --write`; put research in that step's
#   ANNOTATIONS block, which is merged onto the derived rows.
#
# WHY GENERATED: the first cut was hand-assembled from offseason trackers (9 rows). It missed 16 of
#   the 23 team changes among draftable skill players — including A.J. Brown PHI->NE at ADP 13.6 —
#   while carrying Tyler Allgeier at ADP 167, and had no row for the two highest-ADP players in the
#   league (Bijan Robinson 1.6, Jahmyr Gibbs 1.8), both with a changed backfield. A tracker recap is
#   not a frame over the players you actually draft.
#
# SCOPE: FFC PPR 12-team board, snapshot {snap}, skill positions, ADP <= {E.MAX_ADP:.0f}.
#   {len(out)} events over {out['team'].nunique()} teams.
# DERIVED (machine-checked): player, position, team, prev_team, event_type, adp, new_play_caller,
#   play_caller, new_qb, qb, arrivals, departures. Team assignment is DUAL-SOURCED (adp_snapshots +
#   consensus_projections, 0 disagreements); prev_team from weekly {TARGET - 1}; play-caller columns
#   from 16.3b's reference/coaches.csv.
# HAND-RESEARCHED: mechanism, confidence, notes (evidence=derived+web on those rows).
#
# event_type — strongest applicable wins:
#   team_change    on a different team than last season
#   new_to_league  on the board with no {TARGET - 1} snaps (rookie, or missed the year)
#   room_change    stayed put, but a same-position draftable player arrived or left
#   context_only   nothing moved around him, but his team changed play-caller and/or quarterback
# mechanism: trade | free_agent | draft | return | unknown. 'unknown' = NOT YET RESEARCHED.
# new_qb: 1 also when the team has NO quarterback on the ADP board at all (qb='(unsettled)':
#   {TARGET} ARI/ATL/CLE/NYJ/PIT) — those are the least settled rooms, not missing data to skip.
#   Known false positive: fires when an incumbent missed time and a backup led {TARGET - 1} attempts
#   (WAS, Jayden Daniels vs a Marcus Mariota baseline). Left visible, not silently patched.
# arrivals/departures: same-position draftable churn in the room he plays in THIS season.
#   Departures include {TARGET - 1} producers (>={E.MATERIAL_LOAD} car+tgt+att) who left the pool.
#
# ★ USER REVIEW: the derived columns are exhaustive and machine-checked. The review surface is the
#   mechanism/confidence/notes columns: {n_unknown} rows still at mechanism=unknown, {n_soft} below
#   confidence=high. `confidence` grades the ANNOTATION only — the derived facts on every row are
#   dual-sourced regardless of what it says.
"""


def main() -> None:
    write = "--write" in sys.argv
    con = db.connect(read_only=True)

    derived = E.build_event_board(con, TARGET)
    out, orphan = E.merge_annotations(derived, ANNOTATIONS)
    E.assert_events_schema(out)

    print(f"16.5  derived board: {len(out)} events over {out['team'].nunique()} teams "
          f"(ADP <= {E.MAX_ADP:.0f}, skill only)")
    print(E.summarize(out).to_string(index=False))
    print(f"\n      annotations merged: {(out['evidence'] == 'derived+web').sum()} of "
          f"{len(ANNOTATIONS)}   |   mechanism=unknown: {(out['mechanism'] == 'unknown').sum()}")
    for p in orphan:
        why = WITHDRAWN.get(p, "NOT explained in WITHDRAWN — investigate")
        print(f"      withdrawn: {p} — {why}")
        assert p in WITHDRAWN, f"annotation for {p} matches no derived row and is unexplained"

    print(f"\n      context: {int(out['new_play_caller'].sum())} players on a team with a new "
          f"play-caller, {int(out['new_qb'].sum())} with a new/unsettled QB1")
    qb = E.new_qb_map(con, TARGET)
    print("        QB changes: " + ", ".join(f"{t}->{q}" for t, q in sorted(qb.items())))

    tc = out[out["event_type"] == "team_change"].sort_values("adp")
    print(f"\n      the {len(tc)} team changes, by ADP:")
    print(tc[["player", "position", "prev_team", "team", "adp", "mechanism",
              "confidence"]].to_string(index=False))

    # --- gates -----------------------------------------------------------------------------------
    assert len(out) >= 100, "the board is too small to be an exhaustive frame — derivation broke"
    assert out["team"].nunique() >= 28, "most of the league should appear on a real event board"
    assert (out["event_type"] == "team_change").sum() >= 20, "team-change detection broke"
    assert not out["player"].duplicated().any(), "a player appears twice"
    assert (out.loc[out["event_type"] == "new_to_league", "prev_team"].isna()).all(), \
        "a new_to_league row has a prior team"

    if write:
        body = out.to_csv(index=False)
        head, rows = body.split("\n", 1)
        E.EVENTS_CSV.write_text(head + "\n" + _header(con, out) + rows)
        print(f"\nwrote {E.EVENTS_CSV.relative_to(E.EVENTS_CSV.parents[1])}")
    else:
        on_disk = E.load_events()
        if len(on_disk) != len(out):
            print(f"\n! committed board has {len(on_disk)} rows, derivation gives {len(out)} — "
                  "re-run with --write")

    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(json.dumps({
        "n_events": len(out), "n_teams": int(out["team"].nunique()),
        "max_adp": E.MAX_ADP,
        "by_event_type": {k: int(v) for k, v in out["event_type"].value_counts().items()},
        "n_annotated": int((out["evidence"] == "derived+web").sum()),
        "n_mechanism_unknown": int((out["mechanism"] == "unknown").sum()),
        "n_below_high_confidence": int((out["confidence"] != "high").sum()),
        "n_new_play_caller": int(out["new_play_caller"].sum()),
        "n_new_qb": int(out["new_qb"].sum()),
        "qb_changes": {t: q for t, q in sorted(qb.items())},
        "team_changes": tc[["player", "position", "prev_team", "team", "adp"]].to_dict("records"),
        "withdrawn": WITHDRAWN,
    }, indent=2) + "\n")
    print(f"wrote {OUT.relative_to(OUT.parents[1])}")
    print("\n16.5 DONE-BAR: board derived + dual-sourced · schema PASS · exhaustive at ADP "
          f"<= {E.MAX_ADP:.0f}.\n★ GATE: the {int((out['mechanism'] == 'unknown').sum())} "
          "mechanism=unknown rows are unresearched — USER REVIEW owed before 16.6 renders this.")


if __name__ == "__main__":
    main()
